// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

const getStylesEntryPoints = require( './webpack-utils.js' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );

// Utilities.
const path = require( 'path' );

// Add any new entry points by extending the webpack config.
module.exports = {
  ...defaultConfig,
  ...{
    entry: {
      'js/editor':  path.resolve( process.cwd(), 'src/js',   'editor.js'   ),
      ...getStylesEntryPoints()
    },
    plugins: [
      // Include WP's plugin config.
      ...defaultConfig.plugins.filter(
        (plugin) => plugin.constructor.name !== "RtlCssPlugin",
      ),

      // Removes the empty `.js` files generated by webpack but
      // sets it after WP has generated its `*.asset.php` file.
      new RemoveEmptyScriptsPlugin( {
        stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
      } )
    ]
  }
};